apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: dbeans-dev
  name: dbeans-dev
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: dbeans-dev
  project: default
  source:
    path: k8s/overlays/dev
    repoURL: https://github.com/cripsisxyz/chia-dbeans-infra.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
