apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: crossplane-system
  name: crossplane-system
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  project: default
  source:
    path: crossplane-base-deployment-k8s/overlays/crossplane-system
    repoURL: https://gitlab.opensolutions.cloud/opensolutions/cloud-products-infra-admin.git
    targetRevision: feature/synthetix-lab-gcp-resources
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
