apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: synthetix-saas-dev


resources:
  - grafana-pvc.yaml
  - grafana-service.yaml
  - grafana-deployment.yaml

images:
  - name: grafana
    newName: nexusregistry.opensolutions.cloud/synthetix-saas/grafana
    newTag: 9.5.12