---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dataplayer-api
  name: dataplayer-api
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: dataplayer-api
      deployment: dataplayer-api
  template:
    metadata:
      labels:
        app: dataplayer-api
        deployment: dataplayer-api
    spec:
      imagePullSecrets:
        - name: credentials-nexus-registry-datadope
      containers:
        - name: dataplayer-api
          image: dataplayer-api
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: Europe/Madrid
          ports:
            - containerPort: 8000
              name: http-cmdb
              protocol: TCP
          # readinessProbe:
          #   failureThreshold: 3
          #   httpGet:
          #     path: /
          #     port: https-cmdb
          #     scheme: HTTPS
          #   initialDelaySeconds: 60
          #   periodSeconds: 30
          #   successThreshold: 1
          #   timeoutSeconds: 5
          # livenessProbe:
          #   failureThreshold: 3
          #   initialDelaySeconds: 60
          #   periodSeconds: 10s
          #   successThreshold: 1
          #   tcpSocket:
          #     port: 8443
          #   timeoutSeconds: 5
          resources:
            requests:
              cpu: 200m
              memory: 300Mi
            limits:
              cpu: 1000m
              memory: 500Gi
