---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dataplayer-api
  name: dataplayer-api
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: dataplayer-api
      deployment: dataplayer-api
  template:
    metadata:
      labels:
        app: dataplayer-api
        deployment: dataplayer-api
    spec:
      containers:
        - name: dataplayer-api
          image: dataplayer-api
          volumeMounts:
          - name: config-volume
            mountPath: /root/.chia_keys
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: Europe/Madrid
            - name: keys
              value: persistent
          ports:
            - containerPort: 8000
              name: http-cmdb
              protocol: TCP
          livenessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - '/usr/local/bin/docker-healthcheck.sh || exit 1'
            initialDelaySeconds: 60
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - '/usr/local/bin/docker-healthcheck.sh || exit 1'
            initialDelaySeconds: 60
          resources:
            requests:
              cpu: 200m
              memory: 300Mi
            limits:
              cpu: 1000m
              memory: 500Gi
      volumes:
      - name: config-volume
        configMap:
          name: dataplayer-api-keyring
          items:
          - key: keyring.yml
            path: keyring.yml