apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yml
  - service.yml

images:
  - name: dataplayer-api
    newName: europe-west1-docker.pkg.dev/dbeans/dbeans/dataplayer-api
    newTag: 1.0.0

