apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yml
  - service.yml

images:
  - name: dataplayer-api
    newName: nexusregistry.opensolutions.cloud/synthetix-saas/dataplayer-api
    newTag: 0.5.0

