---
apiVersion: v1
kind: Service
metadata:
  name: dataplayer-api
spec:
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: http-cmdb
  selector:
    app: dataplayer-api

